import Head from "next/head";
import Link from "next/link";
import { SiNextdotjs, SiTailwindcss, SiFirebase } from "react-icons/si";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-center justify-center pt-36">
          <h1 className="text-8xl font-extrabold">The Next Gen Social Media</h1>
          <h1 className="text-8xl font-extrabold">That You Need</h1>
        </div>

        <div className="text-center justify-center container">
          <h1 className="text-2xl pt-10 text-gray-600 ">
            Social media app or website, build for training Front End
            Development and build by using Next.js 13, Taillwind CSS, React
            Icons, Toaster, Framer Motion, and Firebase as BaaS.
          </h1>
          <div className="flex flex-col text-center justify-center gap-5 pt-16 pb-40 lg:flex-row">
            <Link
              href="/Auth/Login"
              className="text-xl font-semibold text-white py-3 px-14 rounded-lg bg-gray-700"
            >
              Start Using
            </Link>
            <button className="text-xl font-semibold text-purple-500 py-3 px-14 rounded-lg bg-white shadow-lg outline outline-1 outline-inherit">
              Portfolio
            </button>
          </div>
        </div>

        <div className=" text-center text-white text-2xl justify-center bg-black py-10">
          <h1>Build With</h1>
          <div className="container">
            <div className="flex flex-col text-center justify-center gap-5 pt-16 pb-40 lg:flex-row">
              <button className="flex justify-center items-center font-semibold outline rounded-md py-2 px-10 gap-2">
                Next.js 13 <SiNextdotjs />
              </button>
              <button className="flex justify-center items-center font-semibold outline rounded-md py-2 px-10 gap-2">
                Tailwind <SiTailwindcss />
              </button>
              <button className="flex justify-center items-center font-semibold outline rounded-md py-2 px-10 gap-2">
                Firebase <SiFirebase />
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
